services:
  dagqa:
    container_name: dagqa-app
    image: dagqa-app:latest
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./runs:/app/runs
      - hf-model-cache:/app/hf_cache

volumes:
  dagqa-runs:
  hf-model-cache: